version: "3.9"
services:
  redis:
    image: redis
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  db:
    container_name: postgres_app
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/app/docker/app.sh"]
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

#  celery:
#    build:
#      context: .
#    env_file:
#      - .env
#    container_name: celery_app
#    command: ["/app/docker/celery.sh", "celery"]
##    command: .venv/bin/celery --app=src.tasks.tasks:celery worker -l INFO
#    depends_on:
#      - redis
#
#  flower:
#    build:
#      context: .
#    env_file:
#      - .env
#    container_name: flower_app
#    command: ["/app/docker/celery.sh", "flower"]  # запуск скрипта для запуска celery
#    depends_on:
#      - redis
#      - celery
#    ports:
#      - 5555:5555
