version: "3.9"
services:
  redis:
    image: redis
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/app/docker/app.sh"]
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
